// This file is @generated by prost-build.
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FunctionInfo {
    /// The new Function's ID. It is the client's responsibility to make sure
    /// it is unique among all registered Functions.
    #[prost(string, tag = "1")]
    pub function_id: ::prost::alloc::string::String,
    /// The MiB of memory that need to be allocated to run a sandbox of this
    /// Function.
    ///
    /// Note that this number represents MebiBytes (i.e., the actual number of
    /// required bytes will be calculated by multiplying this number by `2^20`).
    #[prost(uint32, tag = "2")]
    pub memory_mib: u32,
    /// The number of vCPU cores to spawn Sandboxes of this Function with.
    #[prost(uint32, tag = "3")]
    pub vcpu_count: u32,
    /// Command to execute.
    #[prost(string, tag = "4")]
    pub entrypoint: ::prost::alloc::string::String,
}
impl ::prost::Name for FunctionInfo {
    const NAME: &'static str = "FunctionInfo";
    const PACKAGE: &'static str = "snaplace.runtime.fc";
    fn full_name() -> ::prost::alloc::string::String {
        "snaplace.runtime.fc.FunctionInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/snaplace.runtime.fc.FunctionInfo".into()
    }
}
