// This file is @generated by prost-build.
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FunctionInfo {
    /// The new Function's ID. It is the client's responsibility to make sure
    /// it is unique among all registered Functions.
    #[prost(string, tag = "1")]
    pub function_id: ::prost::alloc::string::String,
    /// The MiB of memory that need to be allocated to run a sandbox of this
    /// Function.
    ///
    /// Note that this number represents MebiBytes (i.e., the actual number of
    /// required bytes will be calculated by multiplying this number by `2^20`).
    #[prost(uint32, tag = "2")]
    pub memory_mib: u32,
    #[prost(string, tag = "3")]
    #[serde(rename = "image")]
    pub image_ref: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub parent_snapshot: ::core::option::Option<::prost::alloc::string::String>,
    /// Command to execute (like Docker's `entrypoint` and `cmd`, but
    /// already resolved/merged).
    ///
    /// # TODO
    ///
    /// This field can be populated either by the user that provides this
    /// struct, or by our system using the OCI Image spec's configuration.
    ///
    /// * The first case is the easiest to handle by our system: `Runtime` just
    ///   modifies the `Spec` (e.g., through a template) accordingly.
    /// * The second case requires retrieving the OCI image spec, which requires
    ///   a firecracker-containerd client. At the moment, only `Runtime` has
    ///   such a client. (This is a runtime-dependent operation anyway). Given
    ///   that, there are two cases:
    ///   1. Each `Runtime` can lazily populate `prcess_args` when it receives
    ///      an empty (wrt that) `FunctionInfo`, **right on the critical path**
    ///      and **for every single request** (since it cannot update the
    ///      original `FunctionInfo` that lives in `SandboxPool`'s store. This
    ///      is bad.
    ///   1. The field could be populated at Function registration time, once
    ///      and for all.
    ///      At the moment, we do not support Function registration though: the
    ///      `Orchestrator` is passed a statically pre-populated
    ///      `FunctionMetadataStore` with the required `FunctionInfo`.
    ///      It would make sense, however, to have a separate Registration
    ///      Service that receives `FunctionInfo` and populates the missing
    ///      fields (e.g., `process_args`, but also `parent_snapshot`).
    ///      To do that, for now, such a Registration Service would need a
    ///      firecracker-containerd client; in other words, it would be coupled
    ///      with `Runtime` (possibly an associated type?), which sounds
    ///      reasonable anyway.
    ///      Nevertheless, such a Registration Service would also need write
    ///      access to `FunctionMetadataStore`, or to a separate store which
    ///      would also be accessible (ro?) by `Runtime` (hence `Worker`, hence
    ///      `SandboxPool` too).
    ///
    /// # Notes
    ///
    /// * If none specified, the system will attempt to combine the related
    ///   fields in the image's OCI Image Configuration.
    ///
    /// * This is how containerd and cri-o merge `entrypoint` and `cmd`:
    ///
    ///   * <<https://github.com/containerd/containerd/blob/v1.7.2/pkg/cri/opts/spec_opts.go#L58-L80>>
    ///   * <<https://github.com/cri-o/cri-o/blob/v1.27.0/internal/factory/container/container.go#L562-L598>>
    #[prost(string, optional, tag = "5")]
    pub process_args: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for FunctionInfo {
    const NAME: &'static str = "FunctionInfo";
    const PACKAGE: &'static str = "snaplace.runtime.fcctrd";
    fn full_name() -> ::prost::alloc::string::String {
        "snaplace.runtime.fcctrd.FunctionInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/snaplace.runtime.fcctrd.FunctionInfo".into()
    }
}
