// This file is @generated by prost-build.
/// Runtime-specific metadata for a registered Function.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FunctionInfo {
    /// Kinds of runtime-specific Function info.
    #[prost(oneof = "function_info::RuntimeSpecific", tags = "1, 2")]
    pub runtime_specific: ::core::option::Option<function_info::RuntimeSpecific>,
}
/// Nested message and enum types in `FunctionInfo`.
pub mod function_info {
    /// Kinds of runtime-specific Function info.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum RuntimeSpecific {
        /// Serialized JSON data as plain base64-encoded bytes.
        #[prost(bytes, tag = "1")]
        B64Json(::prost::bytes::Bytes),
        /// Some runtime-specific protobuf type, serialized as `Any`.
        ///
        /// # Note
        ///
        /// The default type URL for a given message type is:
        /// `type.googleapis.com/_packagename_._messagename_`, as per
        /// <<https://protobuf.dev/programming-guides/proto3/#any>.>
        #[prost(message, tag = "2")]
        Proto3(::prost_types::Any),
    }
}
/// `RegisterFunctionRequest` is the request type used in
/// `FunctionRegistration` service's `RegisterFunction` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterFunctionRequest {
    #[prost(message, optional, tag = "1")]
    pub function_info: ::core::option::Option<FunctionInfo>,
    /// Optional per-Function admission-policy overrides.
    ///
    /// Fields left unset inherit the corresponding system-wide defaults from
    /// the admission controller configuration.
    #[prost(message, optional, tag = "2")]
    pub admission: ::core::option::Option<AdmissionOverrides>,
}
/// Runtime-agnostic per-Function overrides for admission queueing and
/// live-instance policy.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdmissionOverrides {
    /// Maximum number of requests that admission may queue for this Function.
    #[prost(uint64, optional, tag = "1")]
    pub max_queued: ::core::option::Option<u64>,
    /// Maximum time a request may remain queued in admission before it is
    /// failed.
    #[prost(message, optional, tag = "2")]
    pub max_queue_delay: ::core::option::Option<::prost_types::Duration>,
    /// Maximum number of live (i.e., *Idle* + *Active*) Workers for this
    /// Function at once. (*Dying* Workers do not count towards this limit.)
    #[prost(uint64, optional, tag = "3")]
    pub max_live_instances: ::core::option::Option<u64>,
}
/// `RegisterFunctionResponse` is the response type used in
/// `FunctionRegistration` service's `RegisterFunction` RPC, and is empty for now.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterFunctionResponse {}
/// `DeregisterFunctionRequest` is the request type used in
/// `FunctionRegistration` service's `DeregisterFunction` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeregisterFunctionRequest {
    /// The unique ID of the (already registered) Function to be deregistered.
    #[prost(string, tag = "1")]
    pub function_id: ::prost::alloc::string::String,
}
/// `DeregisterFunctionResponse` is the response type used in
/// `FunctionRegistration` service's `DeregisterFunction` RPC, and is empty for now.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeregisterFunctionResponse {}
/// `ListFunctionsRequest` is the request type used in `FunctionRegistration`
/// service's `ListFunctions` RPC, and is empty for now.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFunctionsRequest {}
/// `ListFunctionsResponse` is the (streaming) response type used in
/// `FunctionRegistration` service's `ListFunctions` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFunctionsResponse {
    #[prost(message, optional, tag = "1")]
    pub function_info: ::core::option::Option<FunctionInfo>,
}
/// Generated client implementations.
pub mod function_registration_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// `FunctionRegistration` is the gRPC service of snaplace Orchestrator (i.e.,
    /// the "control plane").
    #[derive(Debug, Clone)]
    pub struct FunctionRegistrationClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl FunctionRegistrationClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> FunctionRegistrationClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> FunctionRegistrationClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            FunctionRegistrationClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// `RegisterFunction` registers a new Function with snaplace.
        pub async fn register_function(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterFunctionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterFunctionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snaplace.registration.FunctionRegistration/RegisterFunction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snaplace.registration.FunctionRegistration",
                        "RegisterFunction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// `DeregisterFunction` deregisters an existing Function in snaplace.
        pub async fn deregister_function(
            &mut self,
            request: impl tonic::IntoRequest<super::DeregisterFunctionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeregisterFunctionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snaplace.registration.FunctionRegistration/DeregisterFunction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snaplace.registration.FunctionRegistration",
                        "DeregisterFunction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// `ListFunctions` lists all Functions currently registered with snaplace.
        pub async fn list_functions(
            &mut self,
            request: impl tonic::IntoRequest<super::ListFunctionsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ListFunctionsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snaplace.registration.FunctionRegistration/ListFunctions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snaplace.registration.FunctionRegistration",
                        "ListFunctions",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod function_registration_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with FunctionRegistrationServer.
    #[async_trait]
    pub trait FunctionRegistration: std::marker::Send + std::marker::Sync + 'static {
        /// `RegisterFunction` registers a new Function with snaplace.
        async fn register_function(
            &self,
            request: tonic::Request<super::RegisterFunctionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterFunctionResponse>,
            tonic::Status,
        >;
        /// `DeregisterFunction` deregisters an existing Function in snaplace.
        async fn deregister_function(
            &self,
            request: tonic::Request<super::DeregisterFunctionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeregisterFunctionResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ListFunctions method.
        type ListFunctionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ListFunctionsResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// `ListFunctions` lists all Functions currently registered with snaplace.
        async fn list_functions(
            &self,
            request: tonic::Request<super::ListFunctionsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ListFunctionsStream>,
            tonic::Status,
        >;
    }
    /// `FunctionRegistration` is the gRPC service of snaplace Orchestrator (i.e.,
    /// the "control plane").
    #[derive(Debug)]
    pub struct FunctionRegistrationServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> FunctionRegistrationServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for FunctionRegistrationServer<T>
    where
        T: FunctionRegistration,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snaplace.registration.FunctionRegistration/RegisterFunction" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterFunctionSvc<T: FunctionRegistration>(pub Arc<T>);
                    impl<
                        T: FunctionRegistration,
                    > tonic::server::UnaryService<super::RegisterFunctionRequest>
                    for RegisterFunctionSvc<T> {
                        type Response = super::RegisterFunctionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterFunctionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistration>::register_function(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterFunctionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snaplace.registration.FunctionRegistration/DeregisterFunction" => {
                    #[allow(non_camel_case_types)]
                    struct DeregisterFunctionSvc<T: FunctionRegistration>(pub Arc<T>);
                    impl<
                        T: FunctionRegistration,
                    > tonic::server::UnaryService<super::DeregisterFunctionRequest>
                    for DeregisterFunctionSvc<T> {
                        type Response = super::DeregisterFunctionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeregisterFunctionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistration>::deregister_function(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeregisterFunctionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snaplace.registration.FunctionRegistration/ListFunctions" => {
                    #[allow(non_camel_case_types)]
                    struct ListFunctionsSvc<T: FunctionRegistration>(pub Arc<T>);
                    impl<
                        T: FunctionRegistration,
                    > tonic::server::ServerStreamingService<super::ListFunctionsRequest>
                    for ListFunctionsSvc<T> {
                        type Response = super::ListFunctionsResponse;
                        type ResponseStream = T::ListFunctionsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListFunctionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistration>::list_functions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListFunctionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for FunctionRegistrationServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snaplace.registration.FunctionRegistration";
    impl<T> tonic::server::NamedService for FunctionRegistrationServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
