// This file is @generated by prost-build.
/// Stats related to a single sandbox.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SandboxStats {
    #[prost(uint64, tag = "1")]
    pub invocations: u64,
    #[prost(uint64, tag = "2")]
    pub restorations: u64,
}
/// Control-plane description of a sandbox managed by snaplace.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SandboxInfo {
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub function_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SandboxControlState", tag = "3")]
    pub state: i32,
    #[prost(bool, tag = "4")]
    pub has_snapshot: bool,
    #[prost(message, optional, tag = "5")]
    pub stats: ::core::option::Option<SandboxStats>,
}
/// `PrepareSandboxRequest` is the request type used in `SandboxLifecycle`
/// service's `PrepareSandbox` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareSandboxRequest {
    /// The unique ID of the Function whose sandbox should be prepared.
    #[prost(string, tag = "1")]
    pub function_id: ::prost::alloc::string::String,
    /// The requested provisioning mode. `UNSPECIFIED` is rejected.
    #[prost(enumeration = "SandboxProvisioningMode", tag = "2")]
    pub mode: i32,
    /// Optional best-effort initial keep-alive duration for the freshly
    /// prepared sandbox.
    /// If provided, snaplace uses it instead of consulting its normal
    /// keep-alive assignment policy for this first parking step only.
    /// This is still not a guarantee of lifetime: eviction, shutdown, or
    /// failures may terminate the sandbox earlier.
    #[prost(message, optional, tag = "3")]
    pub initial_keepalive_hint: ::core::option::Option<::prost_types::Duration>,
}
/// `PrepareSandboxResponse` is the response type used in `SandboxLifecycle`
/// service's `PrepareSandbox` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareSandboxResponse {
    /// Information about the prepared sandbox.
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<SandboxInfo>,
}
/// `DestroySandboxRequest` is the request type used in `SandboxLifecycle`
/// service's `DestroySandbox` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DestroySandboxRequest {
    /// The unique ID of the sandbox to destroy.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    /// If false, reject destruction if the sandbox is currently active.
    ///
    /// If absent, defaults to true.
    #[prost(bool, optional, tag = "2")]
    pub allow_if_active: ::core::option::Option<bool>,
    /// If true, also attempt to remove any persisted snapshot state associated
    /// with the sandbox.
    ///
    /// If absent, defaults to false.
    #[prost(bool, optional, tag = "3")]
    pub remove_persisted_snapshot: ::core::option::Option<bool>,
}
/// `DestroySandboxResponse` is the response type used in `SandboxLifecycle`
/// service's `DestroySandbox` RPC.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DestroySandboxResponse {
    /// True if reusable persisted snapshot state still exists after handling
    /// the request; false otherwise.
    #[prost(bool, tag = "1")]
    pub persistent_snapshot_exists: bool,
}
/// `CreateSnapshotRequest` is the request type used in `SandboxLifecycle`
/// service's `CreateSnapshot` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSnapshotRequest {
    /// The unique ID of the sandbox for which a snapshot should be created.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
}
/// `CreateSnapshotResponse` is the response type used in `SandboxLifecycle`
/// service's `CreateSnapshot` RPC.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSnapshotResponse {
    /// The unique ID of the sandbox whose snapshot creation request completed
    /// successfully.
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
}
/// Policy for provisioning the requested sandbox.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SandboxProvisioningMode {
    Unspecified = 0,
    PreferSnapshot = 1,
    RequireSnapshot = 2,
    ForceFresh = 3,
}
impl SandboxProvisioningMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "UNSPECIFIED",
            Self::PreferSnapshot => "PREFER_SNAPSHOT",
            Self::RequireSnapshot => "REQUIRE_SNAPSHOT",
            Self::ForceFresh => "FORCE_FRESH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED" => Some(Self::Unspecified),
            "PREFER_SNAPSHOT" => Some(Self::PreferSnapshot),
            "REQUIRE_SNAPSHOT" => Some(Self::RequireSnapshot),
            "FORCE_FRESH" => Some(Self::ForceFresh),
            _ => None,
        }
    }
}
/// Control-plane state of a sandbox managed by snaplace.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SandboxControlState {
    Active = 0,
    Idle = 1,
    Dying = 2,
    SnapshotOnly = 3,
}
impl SandboxControlState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Active => "ACTIVE",
            Self::Idle => "IDLE",
            Self::Dying => "DYING",
            Self::SnapshotOnly => "SNAPSHOT_ONLY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVE" => Some(Self::Active),
            "IDLE" => Some(Self::Idle),
            "DYING" => Some(Self::Dying),
            "SNAPSHOT_ONLY" => Some(Self::SnapshotOnly),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod sandbox_lifecycle_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// `SandboxLifecycle` is the gRPC service of snaplace Orchestrator used for
    /// mutating sandbox state through the control plane.
    #[derive(Debug, Clone)]
    pub struct SandboxLifecycleClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SandboxLifecycleClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SandboxLifecycleClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SandboxLifecycleClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SandboxLifecycleClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// `PrepareSandbox` creates or restores a sandbox and parks it in a reusable
        /// state for future invocations.
        pub async fn prepare_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::PrepareSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PrepareSandboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snaplace.sandbox.SandboxLifecycle/PrepareSandbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snaplace.sandbox.SandboxLifecycle",
                        "PrepareSandbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// `CreateSnapshot` requests the creation of a snapshot for an existing
        /// sandbox currently managed by snaplace.
        pub async fn create_snapshot(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSnapshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSnapshotResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snaplace.sandbox.SandboxLifecycle/CreateSnapshot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snaplace.sandbox.SandboxLifecycle",
                        "CreateSnapshot",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// `DestroySandbox` requests the destruction of a sandbox currently managed
        /// by snaplace, and/or its snapshot.
        pub async fn destroy_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::DestroySandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DestroySandboxResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snaplace.sandbox.SandboxLifecycle/DestroySandbox",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snaplace.sandbox.SandboxLifecycle",
                        "DestroySandbox",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod sandbox_lifecycle_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SandboxLifecycleServer.
    #[async_trait]
    pub trait SandboxLifecycle: std::marker::Send + std::marker::Sync + 'static {
        /// `PrepareSandbox` creates or restores a sandbox and parks it in a reusable
        /// state for future invocations.
        async fn prepare_sandbox(
            &self,
            request: tonic::Request<super::PrepareSandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PrepareSandboxResponse>,
            tonic::Status,
        >;
        /// `CreateSnapshot` requests the creation of a snapshot for an existing
        /// sandbox currently managed by snaplace.
        async fn create_snapshot(
            &self,
            request: tonic::Request<super::CreateSnapshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSnapshotResponse>,
            tonic::Status,
        >;
        /// `DestroySandbox` requests the destruction of a sandbox currently managed
        /// by snaplace, and/or its snapshot.
        async fn destroy_sandbox(
            &self,
            request: tonic::Request<super::DestroySandboxRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DestroySandboxResponse>,
            tonic::Status,
        >;
    }
    /// `SandboxLifecycle` is the gRPC service of snaplace Orchestrator used for
    /// mutating sandbox state through the control plane.
    #[derive(Debug)]
    pub struct SandboxLifecycleServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SandboxLifecycleServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SandboxLifecycleServer<T>
    where
        T: SandboxLifecycle,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snaplace.sandbox.SandboxLifecycle/PrepareSandbox" => {
                    #[allow(non_camel_case_types)]
                    struct PrepareSandboxSvc<T: SandboxLifecycle>(pub Arc<T>);
                    impl<
                        T: SandboxLifecycle,
                    > tonic::server::UnaryService<super::PrepareSandboxRequest>
                    for PrepareSandboxSvc<T> {
                        type Response = super::PrepareSandboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PrepareSandboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxLifecycle>::prepare_sandbox(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PrepareSandboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snaplace.sandbox.SandboxLifecycle/CreateSnapshot" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSnapshotSvc<T: SandboxLifecycle>(pub Arc<T>);
                    impl<
                        T: SandboxLifecycle,
                    > tonic::server::UnaryService<super::CreateSnapshotRequest>
                    for CreateSnapshotSvc<T> {
                        type Response = super::CreateSnapshotResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateSnapshotRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxLifecycle>::create_snapshot(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSnapshotSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snaplace.sandbox.SandboxLifecycle/DestroySandbox" => {
                    #[allow(non_camel_case_types)]
                    struct DestroySandboxSvc<T: SandboxLifecycle>(pub Arc<T>);
                    impl<
                        T: SandboxLifecycle,
                    > tonic::server::UnaryService<super::DestroySandboxRequest>
                    for DestroySandboxSvc<T> {
                        type Response = super::DestroySandboxResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DestroySandboxRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SandboxLifecycle>::destroy_sandbox(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DestroySandboxSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SandboxLifecycleServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snaplace.sandbox.SandboxLifecycle";
    impl<T> tonic::server::NamedService for SandboxLifecycleServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
